packages:
  - client
  - server-nest

allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': false
  '@sentry/node-cpu-profiler': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
